### PR TITLE
fix for freeing from main 

### PR DESCRIPTION
**Pull request by Nightwing000**

### CODE REVIEW

**Comment by Nightwing000** [comment]
had to delete parser.py because file name was conflicting with some built in file 
mainly the changes are in the traverse_ast function (detects main function)

**Comment by tejas-techstack** [comment]
give me a few minutes i will review the pr

**Comment by tejas-techstack** [comment]
hey your code is working as intended but the way you have solved it is a bit different from what i expected, you have (in a sense) hardcoded it completely and because of this i wont be able to assign 200 points, i will give you 150 points though good work, also as an added bonus i will give you 20 brownie points for being able to run it on windows :)

**Comment by tejas-techstack** [comment]
!bounty 170

**Comment by Nightwing000** [comment]
yeah it's the first approach that occured to me, what were you thinking? Thanks a lot

**Comment by tejas-techstack** [comment]
the way i wanted it solved was to track the variable when it is returned, you will have to keep track of a function call and when that function returns if it does return the variable you then go back and track the variable the return of the function was assigned to, this way you can keep track

**Pull request merged**
