### PR TITLE
save changes

### PR DESCRIPTION
**Pull request by sampada115**

### CODE REVIEW

**Comment by tejas-techstack** [comment]
hey your code isnt exactly working as intended
```c
#include<stdio.h>

int func(int random){
  int *n = malloc(sizeof(int));
  *n = 10;
  printf("%d\n", *n);
  // if it works right there should be one free here
  return 0;
}

int main(){
  func(10);
  int *n = malloc(sizeof(int));
  *n = 15;
  printf("%d\n", *n);
  // if it works right there should be one free here
  return 0;
}
```


just test it for this code (Replace the UserCode.c with this) if it works then just tell me because it doesnt work for me

**Comment by sampada115** [comment]
it works for me

**Comment by tejas-techstack** [comment]
can you show me what is your outCode.c for this input

**Comment by sampada115** [comment]
i got 
10
15

**Comment by tejas-techstack** [comment]
not the output of the program i want to see the OutCode.c file

**Comment by sampada115** [comment]
#include <stdio.h>
#include <stdlib.h>

// Iterative Fibonacci function for better performance
int fibonacci(int n) {
    if (n <= 1) {
        return n;
    }

    int a = 0, b = 1, next;
    for (int i = 2; i <= n; i++) {
        next = a + b;
        a = b;
        b = next;
    }
    return b;
}

int main() {
    int random = 5;
    int num = 10;
    
    // Dynamically allocate memory for n and x
    int *n = (int *)malloc(sizeof(int));
    int *x = (int *)malloc(sizeof(int));

    // Check if memory allocation was successful
    if (n == NULL || x == NULL) {
        printf("Memory allocation failed!\n");
        return 1;
    }
    
    *x = random;
    *n = num;

    printf("Fibonacci sequence up to %d:\n", *n);
    
    for (int i = 0; i < *n; i++) {
        printf("%d\n", fibonacci(i));
    }

    // Free dynamically allocated memory at the end
    free(x);
    free(n);

    return 0;
}

**Comment by tejas-techstack** [comment]
nono before you run the program, you have to **replace UserCode.c** with 
```c
#include<stdio.h>

int func(int random){
  int *n = malloc(sizeof(int));
  *n = 10;
  printf("%d\n", *n);
  // if it works right there should be one free here
  return 0;
}

int main(){
  func(10);
  int *n = malloc(sizeof(int));
  *n = 15;
  printf("%d\n", *n);
  // if it works right there should be one free here
  return 0;
}
```

and then run 
`python3 ParseInject.py UserCode.c OutCode.c references.json`

**Comment by sampada115** [comment]
can i come to 001? if possible?

**Comment by tejas-techstack** [comment]
sure come

**Comment by tejas-techstack** [comment]
!bounty 50

**Pull request closed without merging**
