### PR TITLE
batfile to run the code

### PR DESCRIPTION
**Pull request by Nightwing000**

### CODE REVIEW

**Comment by Nightwing000** [comment]
"smatGC UserCode.c" 
in terminal to run the code

**Comment by tejas-techstack** [comment]
hey i am currently running linux and a batch file is not going to run on it, can you do something about this, otherwise i will have to find a workaround and that will cost you a few points

**Comment by Nightwing000** [comment]
Oh alright I'll look it up how much time do i have ? I'm having dinner so

**Comment by tejas-techstack** [comment]
i will extend your time by 60 minutes, you can have dinner and come back

**Comment by Nightwing000** [comment]
I'm not dual booted on this system finding the script for linux I can do but yea making and testing it isn't possible I think I'll move on to another issue
Can I have the partial points? Thank you so much

**Comment by Nightwing000** [comment]
or if you have a way for me to create the bash file on windows and push it I can

**Comment by tejas-techstack** [comment]
thats fine i will assign 25 points to you

**Comment by tejas-techstack** [comment]
!bounty 25

**Comment by Nightwing000** [comment]
Thanks again :)

**Pull request merged**
